name: OCI Distribution Spec Conformance Tests
description: Validate a registry against the OCI Distribution Spec
author: The Linux Foundation
branding:
  color: blue
  icon: check-circle
inputs: {}
outputs: {}
runs:
  using: docker
  image: docker://ghcr.io/bloodorangeio/distribution-spec/conformance:34e8255
