name: OCI Distribution Spec Conformance Tests
description: Validate a registry against the OCI Distribution Spec
author: The Linux Foundation
branding:
  color: blue
  icon: check-circle
inputs: {}
outputs: {}
runs:
  using: docker
  # TODO: change to "docker://ghcr.io/opencontainers/distribution-spec/conformance:<TAG>"
  image: conformance/Dockerfile
