name: pre-release

on:
  push:
    branches:
      - build-push-image
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.6'
      - name: Prepare
        id: prepare
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ref::ghcr.io/${{ github.repository }}:${VERSION}
      - name: Docker Build
        run: |
          docker build \
            --build-arg VERSION=${{ steps.prepare.outputs.version }} \
            -t ${{ steps.prepare.outputs.ref }} \
            conformance/
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker Push
        run: |
          docker push ${{ steps.prepare.outputs.ref }}
      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
